COMPONENTS := ../HAL .

LINKOPT = -nostubs

OUTPUTFILE := $(SYSROOT)/HAL$(PLATFORM).dll

DYLIBS := Dragonfruit.dll:$(DFLIBBIN)

MOVEEXPR := base=0x80101000

INCDIR := $(HALINCDIR)

include $(REPO)/Project.mk