COMPONENTS := .

OUTPUTFILE := $(SYSROOT)/Test.dll

DYLIBS := OSDLL.dll:$(OSDLLBIN)

MOVEEXPR := mintiadll text=0x200000,data=text+text_size+align,bss=data+data_size+align

INCDIR := ./

include $(REPO)/Project.mk