const ACCESS_EXEC  1
const ACCESS_WRITE 2
const ACCESS_READ  4

const ACCESS_ALL   (ACCESS_WRITE ACCESS_READ | ACCESS_EXEC |)

const ACCESS_WORLD_EXEC  1
const ACCESS_WORLD_WRITE 2
const ACCESS_WORLD_READ  4

const ACCESS_GROUP_EXEC  8
const ACCESS_GROUP_WRITE 16
const ACCESS_GROUP_READ  32

const ACCESS_OWNER_EXEC  64
const ACCESS_OWNER_WRITE 128
const ACCESS_OWNER_READ  256