const OSFILETYPE_FILE        1
const OSFILETYPE_DIRECTORY   2
const OSFILETYPE_CHARDEVICE  3
const OSFILETYPE_BLOCKDEVICE 4

const OSFILETYPE_UNINITIALIZEDFCB 0x10000

const OSFILEFLAG_NOCACHE     1

const OSACCESSFLAG_BLOCK     1