const OSPROCESSCREATEFLAG_DONTINHERITHANDLES 1
const OSPROCESSCREATEFLAG_FORKQUOTA          2
const OSPROCESSCREATEFLAG_DETACHCONSOLE      4

const OSTHREADCREATEFLAG_SUSPENDED 1

extern OSExit { status -- }