const DLLHEAPINITIALSEGMENTS 128

const DLLHEAPSWIFTMAGIC 0xCD
const DLLHEAPFREEMAGIC  0x32

const DLLHEAPSEGMENT_FREE 0
const DLLHEAPSEGMENT_DIRECT 1
const DLLHEAPSEGMENT_PAGE 2
const DLLHEAPSEGMENT_UNINITIALIZED 3

const DLLHEAPBLOCKMINSIZE 32
const DLLHEAPBLOCKBUCKETS (DLLHEAPBLOCKMINSIZE OSPAGESIZE /)

const DLLHEAPSEGMENTSIZEINITIAL 0x8000
const DLLHEAPSEGMENTMAXSIZE     0x80000

const DLLHEAPSEGMENTLENGTHLOOKUPSIZE (DLLHEAPSEGMENTMAXSIZE OSPAGESIZE /)

struct DLLHeapSegment
	DLLHEAPSEGMENTLENGTHLOOKUPSIZE AllocLengthLookup
	4 UsedCount
	4 Type
	4 VAddr
	4 Length
endstruct

struct DLLHeapBlock
	1 Magic
	1 BucketIndex
	2 SegmentIndex
	4 NextFree
endstruct

extern DLLPagePoolAlloc { length -- vaddr ok }
extern DLLPagePoolFree { vaddr -- }