all:
	make -C Cmd
	make -C mem
	make -C cat
	make -C clear
	make -C ls
	make -C ps
	make -C trunc
	make -C mkdir
	make -C rm
	make -C mount
	make -C umount
	make -C dhrystone
	make -C mv
	make -C chown
	make -C chmod
	make -C chgrp
	make -C sync
	make -C echo
	make -C pwd
	make -C ver
	make -C kill
	make -C killall
	make -C cp
	make -C shutdown
	make -C reboot
	make -C crypt
	make -C whoami
	make -C quota
	make -C mousedemo

	make -C launchtty
	make -C login

cleanup:
	make -C Cmd cleanup
	make -C mem cleanup
	make -C cat cleanup
	make -C clear cleanup
	make -C ls cleanup
	make -C ps cleanup
	make -C trunc cleanup
	make -C mkdir cleanup
	make -C rm cleanup
	make -C mount cleanup
	make -C umount cleanup
	make -C dhrystone cleanup
	make -C mv cleanup
	make -C chown cleanup
	make -C chmod cleanup
	make -C chgrp cleanup
	make -C sync cleanup
	make -C echo cleanup
	make -C pwd cleanup
	make -C ver cleanup
	make -C kill cleanup
	make -C killall cleanup
	make -C cp cleanup
	make -C shutdown cleanup
	make -C reboot cleanup
	make -C crypt cleanup
	make -C whoami cleanup
	make -C quota cleanup
	make -C mousedemo cleanup

	make -C launchtty cleanup
	make -C login cleanup