all:
	make -C Cmd
	make -C mem
	make -C cat
	make -C clear
	make -C ls
	make -C ps
	make -C trunc
	make -C mkdir
	make -C rm
	make -C mount
	make -C umount
	make -C dhrystone
	make -C mv

cleanup:
	make -C Cmd cleanup
	make -C mem cleanup
	make -C cat cleanup
	make -C clear cleanup
	make -C ls cleanup
	make -C ps cleanup
	make -C trunc cleanup
	make -C mkdir cleanup
	make -C rm cleanup
	make -C mount cleanup
	make -C umount cleanup
	make -C dhrystone cleanup
	make -C mv cleanup