all:
	make -C cmd
	make -C mem
	make -C cat
	make -C clear
	make -C ls
	make -C ps

cleanup:
	make -C cmd cleanup
	make -C mem cleanup
	make -C cat cleanup
	make -C clear cleanup
	make -C ls cleanup
	make -C ps cleanup