const FRAMEBUFFER 0x02000000
const FRAMEBUFFER_WIDTH  640
const FRAMEBUFFER_HEIGHT 480

const FRAMEBUFFER_SIZE (FRAMEBUFFER_WIDTH FRAMEBUFFER_HEIGHT * 4 * PAGEOFFSETMASK + PAGENUMBERMASK &)

const FRAMEBUFFER_END (FRAMEBUFFER FRAMEBUFFER_SIZE + PAGEOFFSETMASK + PAGENUMBERMASK &)