externptr HALPlatformKernelPageDirectory

#ifdef LIMN2600

#define DIRTY_BIT_CAUSES_FAULT

const KERNELSPACE   0x80000000
const POOLSPACE     0xB8000000
const IDENTITYSPACE 0xC0000000

const IDENTITYSPACEMASK (IDENTITYSPACE ~)

const PAGESIZE  4096
const PAGEOFFSETMASK (PAGESIZE 1 -)
const PAGENUMBERMASK (PAGEOFFSETMASK ~)
const PAGESHIFT 12
const PDSHIFT   22

const PTESIZE 4

const POOLSIZE  (16 1024 * 1024 *)
const POOLPAGES (POOLSIZE PAGESHIFT >>)

const PERPAGETABLESHIFT (PAGESHIFT PAGESHIFT + 2 -)
const PERPAGETABLE (1 PERPAGETABLESHIFT <<)
const PERPAGETABLEOFFSETMASK (PERPAGETABLE 1 -)
const PERPAGETABLENUMBERMASK (PERPAGETABLEOFFSETMASK ~)

#endif