externptr HALPlatformKernelPageDirectory

const POOLSIZE  (8 1024 * 1024 *)
const POOLPAGES (POOLSIZE PAGESHIFT >>)

const VIEWSIZE  (8 1024 * 1024 *)
const VIEWPAGES (VIEWSIZE PAGESHIFT >>)



#ifdef LIMN2600

#define DIRTY_BIT_CAUSES_FAULT 1

const KERNELSPACE   0x80000000
const VIEWSPACE     0xB0000000
const POOLSPACE     0xB8000000
const IDENTITYSPACE 0xC0000000

const KERNELSTRUCTURES 0xA0000000

const IDENTITYSPACEMASK (IDENTITYSPACE ~)

const PAGESIZE  4096
const PAGEOFFSETMASK (PAGESIZE 1 -)
const PAGENUMBERMASK (PAGEOFFSETMASK ~)
const PAGESHIFT 12
const PDSHIFT   22

const PTESIZE 4

const PERPAGETABLESHIFT (PAGESHIFT PAGESHIFT + 2 -)
const PERPAGETABLE (1 PERPAGETABLESHIFT <<)
const PERPAGETABLEOFFSETMASK (PERPAGETABLE 1 -)
const PERPAGETABLENUMBERMASK (PERPAGETABLEOFFSETMASK ~)

#endif



#ifdef FOX32

#define DIRTY_BIT_CAUSES_FAULT 1

const KERNELSPACE   0x80000000
const VIEWSPACE     0xB0000000
const POOLSPACE     0xB8000000
const IDENTITYSPACE 0xC0000000

const KERNELSTRUCTURES 0xA0000000

const IDENTITYSPACEMASK (IDENTITYSPACE ~)

const PAGESIZE  4096
const PAGEOFFSETMASK (PAGESIZE 1 -)
const PAGENUMBERMASK (PAGEOFFSETMASK ~)
const PAGESHIFT 12
const PDSHIFT   22

const PTESIZE 4

const PERPAGETABLESHIFT (PAGESHIFT PAGESHIFT + 2 -)
const PERPAGETABLE (1 PERPAGETABLESHIFT <<)
const PERPAGETABLEOFFSETMASK (PERPAGETABLE 1 -)
const PERPAGETABLENUMBERMASK (PERPAGETABLEOFFSETMASK ~)

#endif